<!DOCTYPE html>
<html>
<head>
	<title>syllabe</title>
	<meta charset="utf-8">
</head>

<body>

    <h1> ߜߋ߲߭ ߠߎ߬ </h1>
        
    <p>
    ߜߋ߲߭ ߦߋ߫ ߛߓߍߘߋ߲߫ ߞߋߟߋ߲߫ ߠߋ߬ ߘߌ߫ ߥߊߟ ߛߓߍߘߋ߲߫ ߝߌ߫ߟߊ߬ ߟߊߞߊ߬ߝߏ߬ߣߍ߲ ߡߍ߲ ߞߊ߬ߙߊ߲߬ ߠߊ߫ ߘߝߊߢߊ߫ ߞߋߟߋ
    </p> 
	<table class = "table_parlante" cellpadding="5px">
		<tr>
			<td>ߓߊ</td>
			<td>ߓߋ</td>
			<td>ߓߌ</td>
			<td>ߓߍ</td>
			<td>ߓߎ</td>
			<td>ߓߏ߭</td>
			<td>ߓߐ</td>
		</tr>
		<tr>
			<td>ߔߊ</td>
			<td>ߔߋ</td>
			<td>ߔߌ</td>
			<td>ߔߍ</td>
			<td>ߔߎ</td>
			<td>ߔߏ߭</td>
			<td>ߔߐ</td>
		</tr>
		<tr>
			<td>ߕߊ</td>
			<td>ߕߋ</td>
			<td>ߕߌ</td>
			<td>ߕߍ</td>
			<td>ߕߎ</td>
			<td>ߕߏ</td>
			<td>ߕߐ</td>
		</tr>
		<tr>
			<td>ߖߊ</td>
			<td>ߖߋ</td>
			<td>ߖߌ</td>
			<td>ߖߍ</td>
			<td>ߖߎ</td>
			<td>ߖߏ</td>
			<td>ߖߐ</td>
		</tr>
		<tr>
			<td>ߗߊ</td>
			<td>ߗߋ </td>
			<td>ߗߌ</td>
			<td>ߗߍ</td>
			<td>ߗߎ</td>
			<td>ߗߏ</td>
			<td>ߗߐ</td>
		</tr>
		<tr>
			<td>ߘߊ</td>
			<td>ߘߋ</td>
			<td>ߘߌ</td>
			<td>ߘߍ</td>
			<td>ߘߎ</td>
			<td>ߘߏ</td>
			<td>ߘߐ</td>
		</tr>
		<tr>
			<td>ߙߊ</td>
			<td>ߙߋ</td>
			<td>ߙߌ</td>
			<td>ߙߍ</td>
			<td>ߙߎ</td>
			<td>ߙߏ</td>
			<td>ߙߐ</td>
		</tr>
		<tr>
			<td>ߛߊ</td>
			<td>ߛߋ</td>
			<td>ߛߌ</td>
			<td>ߛߍ</td>
			<td>ߛߎ</td>
			<td>ߛߏ</td>
			<td>ߛߐ</td>
		</tr>
		<tr>
			<td>ߜߊ</td>
			<td>ߜߋ</td>
			<td>ߜߌ</td>
			<td>ߜߍ</td>
			<td>ߜߎ</td>
			<td>ߜߏ</td>
			<td>ߜߐ</td>
		</tr>
		<tr>
			<td>ߝߊ</td>
			<td>ߝߋ</td>
			<td>ߝߌ</td>
			<td>ߝߍ</td>
			<td>ߝߎ</td>
			<td>ߝߏ</td>
			<td>ߝߐ</td>
		</tr>
		<tr>
			<td>ߞߊ</td>
			<td>ߞߋ</td>
			<td>ߞߌ</td>
			<td>ߞߍ</td>
			<td>ߞߎ</td>
			<td>ߞߏ</td>
			<td>ߞߐ</td>
		</tr>
		<tr>
			<td>ߟߊ</td>
			<td>ߟߋ</td>
			<td>ߟߌ</td>
			<td>ߟߍ</td>
			<td>ߟߎ</td>
			<td>ߟߏ</td>
			<td>ߟߐ</td>
		</tr>
		<tr>
			<td>ߡߊ</td>
			<td>ߡߋ</td>
			<td>ߡߌ</td>
			<td>ߡߍ</td>
			<td>ߡߎ</td>
			<td>ߡߏ</td>
			<td>ߡߐ</td>
		</tr>
		<tr>
			<td>ߢߊ</td>
			<td>ߢߋ</td>
			<td>ߢߌ</td>
			<td>ߢߍ</td>
			<td>ߢߎ</td>
			<td>ߢߏ</td>
			<td>ߢߐ</td>
		</tr>
		<tr>
			<td>ߣߊ</td>
			<td>ߣߋ</td>
			<td>ߣߌ</td>
			<td>ߣߍ</td>
			<td>ߣߎ</td>
			<td>ߣߏ</td>
			<td>ߣߐ</td>
		</tr>
		<tr>
			<td>ߤߊ</td>
			<td>ߤߋ</td>
			<td>ߤߌ</td>
			<td>ߤߍ</td>
			<td>ߤߎ</td>
			<td>ߤߏ</td>
			<td>ߤߐ</td>
		</tr>
		<tr>
			<td>ߥߊ</td>
			<td>ߥߋ</td>
			<td>ߥߌ</td>
			<td>ߥߍ</td>
			<td>ߥߎ</td>
			<td>ߥߏ</td>
			<td>ߥߐ</td>
		</tr>
		<tr>
			<td>ߦߊ</td>
			<td>ߦߋ</td>
			<td>ߦߌ</td>
			<td>ߦߍ</td>
			<td>ߦߎ</td>
			<td>ߦߏ</td>
			<td>ߦߐ</td>
		</tr>
	</table>

    <div class = "cadre_teste" id = "niveau_2" > <?php include "body/teste.php" ?> </div>

    <script src = "js/syllabes.js"></script>
</body>
</html>